#!/bin/bash

- name: configuring payment component
  hosts: payment
  become: yes
  tasks:
  - name: install python3
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3 
    - gcc
    - python3-devel

  - name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: creating system user
    ansible.builtin.user:
      name: roboshop 
      state: present
      system: yes # This parameter makes it a system user
      shell: /sbin/nologin # Typically, system users do not have login shells
      home: /app

  - name: download code to tmp directory
    ansible.builtin.get_url:
      url: https://roboshop-backend-src.s3.us-east-1.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip 
  
  - name: unzipping the file into app directory
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copying payment service file systemctl
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: deamon - reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Enable and start the service
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes