#!/bin/bash

- name: configuring user service
  hosts: user
  become: yes
  tasks:
  - name: disable the default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable the nodejs 20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: installing the nodejs 20 version
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: creating system user
    ansible.builtin.user:
      name: roboshop 
      state: present
      system: yes # This parameter makes it a system user
      shell: /sbin/nologin # Typically, system users do not have login shells
      home: /app

  - name: download code to tmp directory
    ansible.builtin.get_url:
      url: https://roboshop-backend-src.s3.us-east-1.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: changing the app directory
    ansible.builtin.command: cd /app

  - name: unzipping the file into app directory
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    community.general.npm:
      path: /app
      state: present

  - name: copying user service file systemctl
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: deamon - reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Enable and start the service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
  
 

  
  